# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newStartScreen.ui'
#
# Created: Fri Feb 14 09:18:57 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(585, 346)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.startTitel = QtGui.QLabel(self.centralwidget)
        self.startTitel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startTitel.setFont(font)
        self.startTitel.setStyleSheet(_fromUtf8("font: 24pt \"MS Shell Dlg 2\";"))
        self.startTitel.setObjectName(_fromUtf8("startTitel"))
        self.horizontalLayout_3.addWidget(self.startTitel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.startImage = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.startImage.setFont(font)
        self.startImage.setObjectName(_fromUtf8("startImage"))
        self.horizontalLayout_6.addWidget(self.startImage)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.page_2)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 4, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 3, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 4, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.startTest = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.startTest.setFont(font)
        self.startTest.setStyleSheet(_fromUtf8(""))
        self.startTest.setText(_fromUtf8(""))
        self.startTest.setObjectName(_fromUtf8("startTest"))
        self.verticalLayout.addWidget(self.startTest)
        self.startTraining = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.startTraining.setFont(font)
        self.startTraining.setStyleSheet(_fromUtf8(""))
        self.startTraining.setText(_fromUtf8(""))
        self.startTraining.setObjectName(_fromUtf8("startTraining"))
        self.verticalLayout.addWidget(self.startTraining)
        self.chooseQuiz = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.chooseQuiz.setFont(font)
        self.chooseQuiz.setStyleSheet(_fromUtf8(""))
        self.chooseQuiz.setText(_fromUtf8(""))
        self.chooseQuiz.setObjectName(_fromUtf8("chooseQuiz"))
        self.verticalLayout.addWidget(self.chooseQuiz)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8(""))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOptions_2 = QtGui.QMenu(self.menubar)
        self.menuOptions_2.setObjectName(_fromUtf8("menuOptions_2"))
        self.language = QtGui.QMenu(self.menuOptions_2)
        self.language.setObjectName(_fromUtf8("language"))
        self.fontMenu = QtGui.QMenu(self.menuOptions_2)
        self.fontMenu.setObjectName(_fromUtf8("fontMenu"))
        self.menuGames = QtGui.QMenu(self.menubar)
        self.menuGames.setObjectName(_fromUtf8("menuGames"))
        self.menuHilf = QtGui.QMenu(self.menubar)
        self.menuHilf.setObjectName(_fromUtf8("menuHilf"))
        MainWindow.setMenuBar(self.menubar)
        self.quizLoader = QtGui.QAction(MainWindow)
        self.quizLoader.setObjectName(_fromUtf8("quizLoader"))
        self.results = QtGui.QAction(MainWindow)
        self.results.setObjectName(_fromUtf8("results"))
        self.geogame = QtGui.QAction(MainWindow)
        self.geogame.setObjectName(_fromUtf8("geogame"))
        self.actionStandard = QtGui.QAction(MainWindow)
        self.actionStandard.setObjectName(_fromUtf8("actionStandard"))
        self.quizPlatform = QtGui.QAction(MainWindow)
        self.quizPlatform.setObjectName(_fromUtf8("quizPlatform"))
        self.actionQuiz_starten = QtGui.QAction(MainWindow)
        self.actionQuiz_starten.setObjectName(_fromUtf8("actionQuiz_starten"))
        self.actionQuiz_trainieren = QtGui.QAction(MainWindow)
        self.actionQuiz_trainieren.setObjectName(_fromUtf8("actionQuiz_trainieren"))
        self.german = QtGui.QAction(MainWindow)
        self.german.setObjectName(_fromUtf8("german"))
        self.english = QtGui.QAction(MainWindow)
        self.english.setObjectName(_fromUtf8("english"))
        self.actionFd = QtGui.QAction(MainWindow)
        self.actionFd.setObjectName(_fromUtf8("actionFd"))
        self.actionDf = QtGui.QAction(MainWindow)
        self.actionDf.setObjectName(_fromUtf8("actionDf"))
        self.actionDf_2 = QtGui.QAction(MainWindow)
        self.actionDf_2.setObjectName(_fromUtf8("actionDf_2"))
        self.actionDf_3 = QtGui.QAction(MainWindow)
        self.actionDf_3.setObjectName(_fromUtf8("actionDf_3"))
        self.actionFd_2 = QtGui.QAction(MainWindow)
        self.actionFd_2.setObjectName(_fromUtf8("actionFd_2"))
        self.actionContact = QtGui.QAction(MainWindow)
        self.actionContact.setObjectName(_fromUtf8("actionContact"))
        self.actionWebhelp = QtGui.QAction(MainWindow)
        self.actionWebhelp.setObjectName(_fromUtf8("actionWebhelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.french = QtGui.QAction(MainWindow)
        self.french.setObjectName(_fromUtf8("french"))
        self.actionBigger = QtGui.QAction(MainWindow)
        self.actionBigger.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionBigger.setObjectName(_fromUtf8("actionBigger"))
        self.actionSmaller = QtGui.QAction(MainWindow)
        self.actionSmaller.setObjectName(_fromUtf8("actionSmaller"))
        self.actionStandard_2 = QtGui.QAction(MainWindow)
        self.actionStandard_2.setObjectName(_fromUtf8("actionStandard_2"))
        self.language.addAction(self.german)
        self.language.addAction(self.english)
        self.language.addAction(self.french)
        self.fontMenu.addAction(self.actionBigger)
        self.fontMenu.addAction(self.actionSmaller)
        self.fontMenu.addAction(self.actionStandard_2)
        self.menuOptions_2.addAction(self.language.menuAction())
        self.menuOptions_2.addAction(self.fontMenu.menuAction())
        self.menuGames.addAction(self.geogame)
        self.menuGames.addAction(self.quizPlatform)
        self.menuHilf.addAction(self.actionContact)
        self.menuHilf.addAction(self.actionWebhelp)
        self.menuHilf.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOptions_2.menuAction())
        self.menubar.addAction(self.menuGames.menuAction())
        self.menubar.addAction(self.menuHilf.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Quiz", None))
        self.startTitel.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/df/logoFinal.png\"/></p></body></html>", None))
        self.startImage.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "TextLabel", None))
        self.label_9.setText(_translate("MainWindow", "TextLabel", None))
        self.label_3.setText(_translate("MainWindow", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow", "TextLabel", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))
        self.label_10.setText(_translate("MainWindow", "TextLabel", None))
        self.label_8.setText(_translate("MainWindow", "TextLabel", None))
        self.label_6.setText(_translate("MainWindow", "TextLabel", None))
        self.label_4.setText(_translate("MainWindow", "TextLabel", None))
        self.label_2.setText(_translate("MainWindow", "TextLabel", None))
        self.menuOptions_2.setTitle(_translate("MainWindow", "Optionen", None))
        self.language.setTitle(_translate("MainWindow", "Sprache", None))
        self.fontMenu.setTitle(_translate("MainWindow", "Schrift", None))
        self.menuGames.setTitle(_translate("MainWindow", "Weitere Lerngames", None))
        self.menuHilf.setTitle(_translate("MainWindow", "Hilfe", None))
        self.quizLoader.setText(_translate("MainWindow", "Quiz Laden", None))
        self.results.setText(_translate("MainWindow", "Resultate Speichern", None))
        self.geogame.setText(_translate("MainWindow", "das game", None))
        self.actionStandard.setText(_translate("MainWindow", "Standard", None))
        self.quizPlatform.setText(_translate("MainWindow", "plattform für quizzes", None))
        self.actionQuiz_starten.setText(_translate("MainWindow", "Quiz Starten", None))
        self.actionQuiz_trainieren.setText(_translate("MainWindow", "Quiz Trainieren", None))
        self.german.setText(_translate("MainWindow", "Deutsch", None))
        self.english.setText(_translate("MainWindow", "Englisch", None))
        self.actionFd.setText(_translate("MainWindow", "fd", None))
        self.actionDf.setText(_translate("MainWindow", "df", None))
        self.actionDf_2.setText(_translate("MainWindow", "df", None))
        self.actionDf_3.setText(_translate("MainWindow", "df", None))
        self.actionFd_2.setText(_translate("MainWindow", "fd", None))
        self.actionContact.setText(_translate("MainWindow", "Kontakt", None))
        self.actionWebhelp.setText(_translate("MainWindow", "Webhilfe", None))
        self.actionAbout.setText(_translate("MainWindow", "Über", None))
        self.french.setText(_translate("MainWindow", "Französisch", None))
        self.actionBigger.setText(_translate("MainWindow", "Grösser", None))
        self.actionBigger.setShortcut(_translate("MainWindow", "Ctrl+1", None))
        self.actionSmaller.setText(_translate("MainWindow", "Kleiner", None))
        self.actionSmaller.setShortcut(_translate("MainWindow", "Ctrl+-", None))
        self.actionStandard_2.setText(_translate("MainWindow", "Standard", None))
        self.actionStandard_2.setShortcut(_translate("MainWindow", "Ctrl+T", None))

import resources_rc
