# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ausleihe\.qgis2\python\plugins\TestGame\newStartScreen.ui'
#
# Created: Mon Jan 27 14:55:44 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(651, 418)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.startTitel = QtGui.QLabel(self.centralwidget)
        self.startTitel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(24)
        self.startTitel.setFont(font)
        self.startTitel.setStyleSheet(_fromUtf8(""))
        self.startTitel.setObjectName(_fromUtf8("startTitel"))
        self.horizontalLayout_3.addWidget(self.startTitel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(586, 97, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startImage = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.startImage.setFont(font)
        self.startImage.setObjectName(_fromUtf8("startImage"))
        self.horizontalLayout.addWidget(self.startImage)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.startGame = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.startGame.setFont(font)
        self.startGame.setStyleSheet(_fromUtf8(""))
        self.startGame.setText(_fromUtf8(""))
        self.startGame.setObjectName(_fromUtf8("startGame"))
        self.verticalLayout.addWidget(self.startGame)
        self.startTraining = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.startTraining.setFont(font)
        self.startTraining.setStyleSheet(_fromUtf8(""))
        self.startTraining.setText(_fromUtf8(""))
        self.startTraining.setObjectName(_fromUtf8("startTraining"))
        self.verticalLayout.addWidget(self.startTraining)
        self.chooseQuiz = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.chooseQuiz.setFont(font)
        self.chooseQuiz.setStyleSheet(_fromUtf8(""))
        self.chooseQuiz.setText(_fromUtf8(""))
        self.chooseQuiz.setObjectName(_fromUtf8("chooseQuiz"))
        self.verticalLayout.addWidget(self.chooseQuiz)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8(""))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem3 = QtGui.QSpacerItem(586, 75, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.dataMenu = QtGui.QMenu(self.menubar)
        self.dataMenu.setObjectName(_fromUtf8("dataMenu"))
        self.menuLetzte_Quizzes = QtGui.QMenu(self.dataMenu)
        self.menuLetzte_Quizzes.setObjectName(_fromUtf8("menuLetzte_Quizzes"))
        self.menuOptions_2 = QtGui.QMenu(self.menubar)
        self.menuOptions_2.setObjectName(_fromUtf8("menuOptions_2"))
        self.language = QtGui.QMenu(self.menuOptions_2)
        self.language.setObjectName(_fromUtf8("language"))
        self.fontMenu = QtGui.QMenu(self.menuOptions_2)
        self.fontMenu.setObjectName(_fromUtf8("fontMenu"))
        self.menuGames = QtGui.QMenu(self.menubar)
        self.menuGames.setObjectName(_fromUtf8("menuGames"))
        self.menuHilf = QtGui.QMenu(self.menubar)
        self.menuHilf.setObjectName(_fromUtf8("menuHilf"))
        MainWindow.setMenuBar(self.menubar)
        self.quizLoader = QtGui.QAction(MainWindow)
        self.quizLoader.setObjectName(_fromUtf8("quizLoader"))
        self.results = QtGui.QAction(MainWindow)
        self.results.setObjectName(_fromUtf8("results"))
        self.geogame = QtGui.QAction(MainWindow)
        self.geogame.setObjectName(_fromUtf8("geogame"))
        self.actionStandard = QtGui.QAction(MainWindow)
        self.actionStandard.setObjectName(_fromUtf8("actionStandard"))
        self.quizPlatform = QtGui.QAction(MainWindow)
        self.quizPlatform.setObjectName(_fromUtf8("quizPlatform"))
        self.actionQuiz_starten = QtGui.QAction(MainWindow)
        self.actionQuiz_starten.setObjectName(_fromUtf8("actionQuiz_starten"))
        self.actionQuiz_trainieren = QtGui.QAction(MainWindow)
        self.actionQuiz_trainieren.setObjectName(_fromUtf8("actionQuiz_trainieren"))
        self.german = QtGui.QAction(MainWindow)
        self.german.setObjectName(_fromUtf8("german"))
        self.english = QtGui.QAction(MainWindow)
        self.english.setObjectName(_fromUtf8("english"))
        self.actionFd = QtGui.QAction(MainWindow)
        self.actionFd.setObjectName(_fromUtf8("actionFd"))
        self.actionDf = QtGui.QAction(MainWindow)
        self.actionDf.setObjectName(_fromUtf8("actionDf"))
        self.actionDf_2 = QtGui.QAction(MainWindow)
        self.actionDf_2.setObjectName(_fromUtf8("actionDf_2"))
        self.actionDf_3 = QtGui.QAction(MainWindow)
        self.actionDf_3.setObjectName(_fromUtf8("actionDf_3"))
        self.actionFd_2 = QtGui.QAction(MainWindow)
        self.actionFd_2.setObjectName(_fromUtf8("actionFd_2"))
        self.actionContact = QtGui.QAction(MainWindow)
        self.actionContact.setObjectName(_fromUtf8("actionContact"))
        self.actionWebhelp = QtGui.QAction(MainWindow)
        self.actionWebhelp.setObjectName(_fromUtf8("actionWebhelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.french = QtGui.QAction(MainWindow)
        self.french.setObjectName(_fromUtf8("french"))
        self.actionBigger = QtGui.QAction(MainWindow)
        self.actionBigger.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionBigger.setObjectName(_fromUtf8("actionBigger"))
        self.actionSmaller = QtGui.QAction(MainWindow)
        self.actionSmaller.setObjectName(_fromUtf8("actionSmaller"))
        self.menuLetzte_Quizzes.addAction(self.actionFd)
        self.menuLetzte_Quizzes.addAction(self.actionDf)
        self.menuLetzte_Quizzes.addAction(self.actionDf_2)
        self.menuLetzte_Quizzes.addAction(self.actionDf_3)
        self.menuLetzte_Quizzes.addAction(self.actionFd_2)
        self.dataMenu.addAction(self.quizLoader)
        self.dataMenu.addAction(self.results)
        self.dataMenu.addSeparator()
        self.dataMenu.addAction(self.actionQuiz_starten)
        self.dataMenu.addAction(self.actionQuiz_trainieren)
        self.dataMenu.addAction(self.menuLetzte_Quizzes.menuAction())
        self.language.addAction(self.german)
        self.language.addAction(self.english)
        self.language.addAction(self.french)
        self.fontMenu.addAction(self.actionBigger)
        self.fontMenu.addAction(self.actionSmaller)
        self.menuOptions_2.addAction(self.language.menuAction())
        self.menuOptions_2.addAction(self.fontMenu.menuAction())
        self.menuGames.addAction(self.geogame)
        self.menuGames.addAction(self.quizPlatform)
        self.menuHilf.addAction(self.actionContact)
        self.menuHilf.addAction(self.actionWebhelp)
        self.menuHilf.addAction(self.actionAbout)
        self.menubar.addAction(self.dataMenu.menuAction())
        self.menubar.addAction(self.menuOptions_2.menuAction())
        self.menubar.addAction(self.menuGames.menuAction())
        self.menubar.addAction(self.menuHilf.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Quiz-Plugin", None))
        self.startTitel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:normal; color:#000000;\">Quiz</span></p></body></html>", None))
        self.startImage.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.dataMenu.setTitle(_translate("MainWindow", "Datei", None))
        self.menuLetzte_Quizzes.setTitle(_translate("MainWindow", "Letzte Quizzes", None))
        self.menuOptions_2.setTitle(_translate("MainWindow", "Optionen", None))
        self.language.setTitle(_translate("MainWindow", "Sprache", None))
        self.fontMenu.setTitle(_translate("MainWindow", "Schrift", None))
        self.menuGames.setTitle(_translate("MainWindow", "Weitere Lerngames", None))
        self.menuHilf.setTitle(_translate("MainWindow", "Hilfe", None))
        self.quizLoader.setText(_translate("MainWindow", "Quiz Laden", None))
        self.results.setText(_translate("MainWindow", "Resultate Speichern", None))
        self.geogame.setText(_translate("MainWindow", "das game", None))
        self.actionStandard.setText(_translate("MainWindow", "Standard", None))
        self.quizPlatform.setText(_translate("MainWindow", "plattform für quizzes", None))
        self.actionQuiz_starten.setText(_translate("MainWindow", "Quiz Starten", None))
        self.actionQuiz_trainieren.setText(_translate("MainWindow", "Quiz Trainieren", None))
        self.german.setText(_translate("MainWindow", "Deutsch", None))
        self.english.setText(_translate("MainWindow", "Englisch", None))
        self.actionFd.setText(_translate("MainWindow", "fd", None))
        self.actionDf.setText(_translate("MainWindow", "df", None))
        self.actionDf_2.setText(_translate("MainWindow", "df", None))
        self.actionDf_3.setText(_translate("MainWindow", "df", None))
        self.actionFd_2.setText(_translate("MainWindow", "fd", None))
        self.actionContact.setText(_translate("MainWindow", "Kontakt", None))
        self.actionWebhelp.setText(_translate("MainWindow", "Webhilfe", None))
        self.actionAbout.setText(_translate("MainWindow", "Über", None))
        self.french.setText(_translate("MainWindow", "Französisch", None))
        self.actionBigger.setText(_translate("MainWindow", "Grösser", None))
        self.actionBigger.setShortcut(_translate("MainWindow", "Ctrl+1", None))
        self.actionSmaller.setText(_translate("MainWindow", "Kleiner", None))
        self.actionSmaller.setShortcut(_translate("MainWindow", "Ctrl+-", None))

